- name: Deploy backend application on Kubernetes
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Create deployment
      k8s:
        kubeconfig: "~/.kube/config"
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: ordear-backend-deployment
            namespace: themenufy
            labels:
              app: ordearbackend-app
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: ordearbackend-app
            template:
              metadata:
                labels:
                  app: ordearbackend-app
              spec:
                containers:
                  - name: ordear-rest-api
                    image: taharejeb97/ordear:v1.6.2-prod
                    ports:
                      - containerPort: 5555
                nodeSelector:
                     kubernetes.io/hostname: worker2  
        # context: "kubernetes-admin@kubernetes"
        # api_key: "kubeconfig-user-tz4cgnc87h:c5bblz84ddpxbmbnr9wf6fn5n4rw8k8xdn4t4wjgwcj7xq9fzxprsg"
       # verify_ssl: false

    - name: Create service
      k8s:
        state: present
        kubeconfig: "~/.kube/config"
        verify_ssl: no
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: ordear-backend-service
            namespace: themenufy
            labels:
              app: ordearbackend-app
          spec:
            selector:
              app: ordearbackend-app
            ports:
              - protocol: TCP
                port: 4046
                targetPort: 5555
                nodePort: 32299
            type: NodePort
